orbs:
  docker: circleci/docker@2.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.2
version: 2.1
executors:
  docker-py3-ghp:
    docker:
      - image: cimg/python:3.9
    resource_class: medium
  docker-sonarcloud:
    docker:
      - image: cimg/node:17.0.1
    resource_class: medium
jobs:
  static-analysis:
    executor: docker-sonarcloud
    steps:
      - checkout
      - sonarcloud/scan
workflows:
  version: 2
  build:
    jobs:
      - static-analysis:
          filters:
            branches:
              ignore:
                - master
          context:
            - sonarcloud.io
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/alpine-cmake:latest"
          image: "tprrt/alpine-cmake"
          path: alpine-cmake
          docker-context: alpine-cmake
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/alpine-pxe:latest"
          image: "tprrt/alpine-pxe"
          path: alpine-pxe
          docker-context: alpine-pxe
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-buildroot:latest"
          image: "tprrt/debian-buildroot"
          path: debian-buildroot
          docker-context: debian-buildroot
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-cross:latest"
          image: "tprrt/debian-cross"
          path: debian-cross
          docker-context: debian-cross
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-latex:latest"
          image: "tprrt/debian-latex"
          path: debian-latex
          docker-context: debian-latex
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-oe:latest"
          image: "tprrt/debian-oe"
          path: debian-oe
          docker-context: debian-oe
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/fedora-dev:latest"
          image: "tprrt/fedora-dev"
          path: fedora-dev
          docker-context: fedora-dev
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: false
  build-publish:
    jobs:
      - static-analysis:
          filters:
            branches:
              only:
                - master
          context:
            - sonarcloud.io
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/alpine-cmake:latest"
          image: "tprrt/alpine-cmake"
          path: alpine-cmake
          docker-context: alpine-cmake
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/alpine-pxe:latest"
          image: "tprrt/alpine-pxe"
          path: alpine-pxe
          docker-context: alpine-pxe
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-buildroot:latest"
          image: "tprrt/debian-buildroot"
          path: debian-buildroot
          docker-context: debian-buildroot
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-cross:latest"
          image: "tprrt/debian-cross"
          path: debian-cross
          docker-context: debian-cross
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-latex:latest"
          image: "tprrt/debian-latex"
          path: debian-latex
          docker-context: debian-latex
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/debian-oe:latest"
          image: "tprrt/debian-oe"
          path: debian-oe
          docker-context: debian-oe
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
      - docker/publish:
          filters:
            branches:
              ignore:
                - master
          requires:
            - static-analysis
          context:
            - docker.io
          cache_from: "tprrt/fedora-dev:latest"
          image: "tprrt/fedora-dev"
          path: fedora-dev
          docker-context: fedora-dev
          tag: latest
          registry: docker.io
          update-description: false
          use-docker-credentials-store: true
          dockerfile: Dockerfile
          readme: README.rst
          deploy: true
